### ISSUE TITLE
Cannot compile with Golang 1.12.9

### ISSUE THREAD

**Issue by prabhash1785** [spacemonkeygo/openssl#130]
I see multiple issues while compiling with 1.12.9
- utils sub-module is not a module hence it fails to resolve this.
- logger dependency does not resolve because spacelogger is not a module
- After fixing above code, compiler fails to resolve Ctx. However I see it compiles for Mac. Wondering if there are any know issues with Linux compilation?
```
GOOS=linux GOARCH=amd64 go build -v
github.com/spacemonkeygo/openssl
# github.com/spacemonkeygo/openssl
openssl/net.go:24:7: undefined: Ctx
```
